spring:
   application:
      name: service-performance
   profiles:
      active: development


---
#
# development configuration
#
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7778


---
#
# production configuration
#
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://34.64.240.101:7778
